update_vm_image:
    only: ["master"]
    script:
    - update-vm-image
    tags: ["docker-builder"]

build_images:
    only: ["master"]
    script:
    - cgc-build network-dude
    tags: ["docker-builder"]
